### ISSUE TITLE
Feedback en feedforward in de interface

### ISSUE THREAD

**Issue by KoopReynders** [vsheo/fix-the-flow-interactive-website#11]
Probeer in de interface duidelijk te maken wat de verschillende onderdelen zijn en wat een gebruiker kan doen. 
Bv de radionav is het nu niet duidelijk voor een gebruiker wat het is en wat je er mee kan. Ook als die wordt opengeklapt, moet je even een titel tonen met wat het is.

Hier ontbreekt een label
<img width="90" alt="image" src="https://github.com/user-attachments/assets/639eef43-3b09-4cf2-93e3-2bf65801888b">

Hier mist een titeltje
<img width="191" alt="image" src="https://github.com/user-attachments/assets/8891dec6-f7d0-4849-ae9e-adf60edb23d3">

**Comment by vsheo** [comment]
Ik heb deze feedback hier verwerkt:
https://github.com/vsheo/fix-the-flow-interactive-website/issues/13

**Comment by KoopReynders** [comment]
Mooi, ik zie de titel bij het overzicht van de radiozenders.
<img width="253" alt="image" src="https://github.com/user-attachments/assets/054ce337-87b7-4ab3-97bb-020b447d89fa" />
Hier mist nog wel een label!

**Comment by KoopReynders** [comment]
Bij mij ziet het menu er wel gek uit, ik denk niet dat dit de bedoeling is zo midden eind e pagina? Ik maak gebruik van Safari versie 17.6. 

Als je het men nog wil verbeteren, dan kun je ook een a gebruiken in plaat van een button om het menu te openen. Dan kan je ervoor zorgen dat het menu het ook doet zonder javascript... Dat is de volgende stap, zorgen dat je website het altijd, doet, voor iedereen ... Check de repo van Marcin. Hij heeft het heel mooi opgelost. 

<img width="686" alt="image" src="https://github.com/user-attachments/assets/83884490-43bb-4a1b-a0b8-a58275df74a8" />

**Comment by vsheo** [comment]
dank je wel voor de feedback.

Ik had mijn navigatie menu kort voor de sprint review veranderd.
Het was me niet gelukt om dit nog te verbeteren voor de sprint review.

Tijdens het testen had ik dit wel gezien, en een issue ervoor gemaakt.
https://github.com/vsheo/fix-the-flow-interactive-website/issues/16#:~:text=de%20navigatie%20menu%20komt%20te%20ver%20naar%20rechts%20op%20het%20scherm%20(tablet%20en%20desktop%20versie)
