### ISSUE TITLE
sprint 5: User Interface Design

### ISSUE THREAD

**Issue by vsheo** [vsheo/fix-the-flow-interactive-website#4]
aanpak:
https://github.com/fdnd-task/fix-the-flow-interactive-website/blob/main/docs/user-interface-design.md#aanpak

- Een user story maken
- wireflow maken
- javascript schrijven, om de interactie werkend te krijgen

**Comment by vsheo** [comment]
User story
Op de mobiele versie van mijn website wil ik een button aan de rechterkant van het scherm.
Als er op deze button geklikt wordt dan slide er een nav, met CSS op beeld.

In deze nav zijn er 4 buttons, 1 voor elke radiozender.
Als er op een button geklikt wordt dan gaat het programma van die radiozender open.

**Comment by vsheo** [comment]
### Wireflow
![Image](https://github.com/user-attachments/assets/3f401bfb-344b-4c69-956d-11ba6ed1f0b6)

**Comment by TomDeeterink1** [comment]
**User story**

User story is wat aan de korte kant, maar is wel duidelijk!

**Wireflow**

Je wireflow is duidelijk, let er wel op dat je wat netter gaat tekenen. Dit is namelijk belangrijke bewijslast die je goed kan gebruiken! Wellicht is het interessant om wireflows te maken in figma? 

Het enige wat ik nog mis is een breakdown van de js :).

**User interactie**

Goed idee! Ik denk ook dat dit echt een meerwaarde heeft voor de gebruiker. Alleen de positie/ grootte van de button zou ik in het design iets subtieler maken.

Voorderest goed op weg!

**Comment by vsheo** [comment]
### nieuwe wireflow
![UI_wireflow_4](https://github.com/user-attachments/assets/5a51cbbf-8636-4922-aa70-7d5ee13869cb)

**Comment by vsheo** [comment]
### Breakdown schets in de wireflow

![wireflow_breakdown](https://github.com/user-attachments/assets/b2cf97d3-d7f8-49c2-a494-bc6c8b8d66e0)

**Comment by vsheo** [comment]
de radio nav gaat nu open en dicht.
de volgende stap is het programma veranderen als er op een radiozender geklikt wordt

**Comment by vsheo** [comment]
de javascript voor het veranderen van de radiozender werkt.
maar er is een "bug", het werkt alleen goed als alle buttens een paar keer geklikt worden.

ik denk dat dit te maken heeft met met de volgorde van mijn instructies in de javaScript.;
